version: '2'
services:
 # ui:
 #   build: ./react-learning
 #   ports:
 #     - '3000:3000'
 #   depends_on:
 #     - api
 # api:
 #   build: ./server
 #   ports:
 #     - '7000:7000'
 #   depends_on:
 #     - mongo
  mongo:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'